//
// Created by victor on 23/12/2017.
//

#ifndef WECHAT_COMMAND_DEF_H
#define WECHAT_COMMAND_DEF_H
typedef int COMMAND_DEF;

const COMMAND_DEF SIGN_UP = 0;
const COMMAND_DEF LOG_IN = SIGN_UP +1;
const COMMAND_DEF LOG_OUT = LOG_IN + 1;
const COMMAND_DEF ADD = LOG_OUT + 1;
const COMMAND_DEF LS = ADD + 1;
const COMMAND_DEF SEARCH = LS + 1;
const COMMAND_DEF CHAT = SEARCH + 1;
const COMMAND_DEF MESSAGE = CHAT + 1;
const COMMAND_DEF FILESEND = MESSAGE + 1;
const COMMAND_DEF REMESSAGE = FILESEND + 1;
const COMMAND_DEF REFILE = REMESSAGE + 1;
const COMMAND_DEF PROFILE = REFILE + 1;
const COMMAND_DEF SYNC = PROFILE + 1;
const COMMAND_DEF CONNECT_ACK = SYNC + 1;

#endif //WECHAT_COMMAND_DEF_H
