//
// Created by victor on 23/12/2017.
//

#ifndef WECHAT_COMMAND_DEF_H
#define WECHAT_COMMAND_DEF_H
typedef int COMMAND_DEF;

const COMMAND_DEF SIGN_UP = 0;
const COMMAND_DEF LOG_IN = SIGN_UP +1;
const COMMAND_DEF LOG_OUT = LOG_IN + 1;
const COMMAND_DEF ADD = LOG_OUT + 1;
const COMMAND_DEF LS = ADD + 1;
const COMMAND_DEF SEARCH = LS + 1;
const COMMAND_DEF CHAT = SEARCH + 1;
const COMMAND_DEF MESSAGE = CHAT + 1;
const COMMAND_DEF FILESEND = MESSAGE + 1;
const COMMAND_DEF REMESSAGE = FILESEND + 1;
const COMMAND_DEF REFILE = REMESSAGE + 1;
const COMMAND_DEF PROFILE = REFILE + 1;
const COMMAND_DEF SYNC = PROFILE + 1;

const COMMAND_DEF CONNECT_ACK = SYNC + 1;
const COMMAND_DEF SIGN_UP_ACK = CONNECT_ACK + 1;
const COMMAND_DEF LOG_IN_ACK = SIGN_UP_ACK + 1;
const COMMAND_DEF ADD_ACK = LOG_IN_ACK + 1;
const COMMAND_DEF LS_ACK = ADD_ACK + 1;
const COMMAND_DEF SEARCH_ACK = LS_ACK + 1;
const COMMAND_DEF CHAT_ACK = SEARCH_ACK + 1;
const COMMAND_DEF NEW_MESSAGE = CHAT_ACK + 1;
const COMMAND_DEF NEW_FILE = NEW_MESSAGE + 1;
const COMMAND_DEF OLD_MESSAGE = NEW_FILE + 1;
const COMMAND_DEF OLD_FILE = OLD_MESSAGE + 1;
const COMMAND_DEF PROFILE_ACK = OLD_FILE + 1;
const COMMAND_DEF SYNC_ACK = PROFILE_ACK + 1;
const COMMAND_DEF MESSAGE_ACK = SYNC_ACK + 1;
const COMMAND_DEF LOG_OUT_ACK = MESSAGE_ACK + 1;

const COMMAND_DEF EXIT = LOG_OUT_ACK+1;
const COMMAND_DEF EXIT_ACK = EXIT + 1;

const COMMAND_DEF FILE_START = EXIT_ACK + 1;
const COMMAND_DEF FILE_START_ACK = FILE_START+1;
const COMMAND_DEF FILE_END = FILE_START_ACK+1;
const COMMAND_DEF FILE_END_ACK = FILE_END+1;
const COMMAND_DEF FILE_GET_ACK = FILE_END_ACK+1;
#endif //WECHAT_COMMAND_DEF_H
